# Generated by Django 4.2 on 2026-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBiodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='सरल क्रमांक (Serial Number)')),
                ('full_name', models.CharField(max_length=255, verbose_name='नाम (Name)')),
                ('caste', models.CharField(default='Gond', max_length=100, verbose_name='जाति (Caste)')),
                ('gotra', models.CharField(max_length=100, verbose_name='गोत्र (Gotra)')),
                ('deity_number', models.CharField(max_length=50, verbose_name='देव संख्या (Deity Number)')),
                ('father_name', models.CharField(max_length=255, verbose_name="पिता का नाम (Father's Name)")),
                ('mother_name', models.CharField(max_length=255, verbose_name="माता का नाम (Mother's Name)")),
                ('maternal_uncle_gotra', models.CharField(max_length=100, verbose_name="मामा का गोत्र (Maternal Uncle's Gotra)")),
                ('family_status', models.TextField(verbose_name='पारिवारिक स्थिति (Family Status)')),
                ('complexion', models.CharField(max_length=50, verbose_name='रंग (Complexion)')),
                ('height', models.CharField(max_length=20, verbose_name='कद (Height)')),
                ('date_of_birth', models.DateField(verbose_name='जन्मतिथि (Date of Birth)')),
                ('education', models.TextField(verbose_name='शिक्षा (Education)')),
                ('occupation', models.CharField(default='निरंक', max_length=255, verbose_name='वर्तमान व्यवसाय (Current Occupation)')),
                ('address', models.TextField(verbose_name='पूरा पता (Full Address)')),
                ('guardian_mobile', models.CharField(max_length=15, verbose_name='पालक या रिश्तेदार का मोबाईल नंबर (Guardian Mobile)')),
            ],
            options={
                'verbose_name': 'Biodata Profile',
                'verbose_name_plural': 'Biodata Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
