# Generated by Django 4.2 on 2026-02-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybiodata',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='biodata_photos/', verbose_name='फोटो (Photo)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='address',
            field=models.TextField(verbose_name='पूरा पता (Address)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='guardian_mobile',
            field=models.CharField(max_length=15, verbose_name='पालक का मोबाईल (Mobile)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='maternal_uncle_gotra',
            field=models.CharField(max_length=100, verbose_name='मामा का गोत्र (Mama Gotra)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='occupation',
            field=models.CharField(default='निरंक', max_length=255, verbose_name='वर्तमान व्यवसाय'),
        ),
    ]
