# Generated by Django 4.2 on 2026-02-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_communitybiodata_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybiodata',
            name='annual_income',
            field=models.CharField(blank=True, max_length=100, verbose_name='वार्षिक आय (Annual Income)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='जन्म स्थान (Birth Place)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='birth_time',
            field=models.TimeField(blank=True, null=True, verbose_name='जन्म समय (Birth Time)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='रक्त समूह (Blood Group)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='candidate_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='स्वयं का मोबाईल (Candidate Mobile)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='शहर/ग्राम (City/Village)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='जिला (District)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ईमेल (Email)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, verbose_name='पिता का व्यवसाय'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male/पुरुष'), ('F', 'Female/महिला'), ('O', 'Other/अन्य')], max_length=1, null=True, verbose_name='लिंग (Gender)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='सक्रिय है? (Is Active)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='marital_status',
            field=models.CharField(choices=[('Unmarried', 'अविवाहित (Unmarried)'), ('Married', 'विवाहित (Married)'), ('Divorced', 'तलाकशुदा (Divorced)'), ('Widow/Widower', 'विधवा/विधुर (Widow/Widower)')], default='Unmarried', max_length=20, verbose_name='वैवाहिक स्थिति (Marital Status)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='state',
            field=models.CharField(default='Chhattisgarh', max_length=100, verbose_name='राज्य (State)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='वजन (Weight in kg)'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='work_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='कार्य स्थल (Work Location)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='family_status',
            field=models.TextField(help_text='भाई-बहन की जानकारी', verbose_name='पारिवारिक स्थिति (Family Status)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='guardian_mobile',
            field=models.CharField(max_length=15, verbose_name='पालक का मोबाईल (Guardian Mobile)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='सरल क्रमांक (Serial Number)'),
        ),
    ]
