# Generated by Django 4.2 on 2026-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_communitybiodata_annual_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(max_length=255, verbose_name='जोड़े का नाम')),
                ('wedding_date', models.DateField(verbose_name='शादी की तिथि')),
                ('image', models.ImageField(upload_to='success_stories/', verbose_name='जोड़े की फोटो')),
                ('story_text', models.TextField(verbose_name='सफलता की कहानी')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
