# Generated by Django 4.2 on 2026-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_communitybiodata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitybiodata',
            name='user',
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='address',
            field=models.TextField(verbose_name='पूरा पता'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('Low', 'कम आय (₹7000 से कम)'), ('Medium', 'मध्यम आय (₹7000 – ₹20,000)'), ('High', 'अधिक आय (₹20,000 से अधिक)')], max_length=100, null=True, verbose_name='वार्षिक आय'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='रक्त समूह'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='candidate_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='स्वयं का मोबाईल'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='caste',
            field=models.CharField(choices=[('Agariya', 'अगरिया'), ('Andh', 'अंध'), ('Baiga', 'बैगा'), ('Baina', 'बैना'), ('Bharia', 'भारिया भूमिया'), ('Bhattra', 'भतरा'), ('Bhil', 'भील'), ('Bhil Mina', 'भील मीणा'), ('Bhunjia', 'भुंजिया'), ('Biar', 'बियार'), ('Binjhwar', 'बिंझवार'), ('Birhor', 'बिरहुल'), ('Damor', 'डामोर'), ('Dhanwar', 'धनवार'), ('Gadaba', 'गदबा'), ('Gond', 'गोंड'), ('Halba', 'हल्बा'), ('Kamar', 'कमार'), ('Karku', 'कारकू'), ('Kawar', 'कंवर'), ('Khairwar', 'खैरवार'), ('Kharia', 'खड़िया'), ('Kondh', 'कोंध'), ('Kol', 'कोल'), ('Kolam', 'कोलम'), ('Korku', 'कोरकू'), ('Korwa', 'कोरवा'), ('Majhi', 'मांझी'), ('Majhwar', 'मंझवार'), ('Mawasi', 'मवासी'), ('Munda', 'मुंडा'), ('Nagesia', 'नगेसिया'), ('Oraon', 'उरांव'), ('Pao', 'पाव'), ('Pardhan', 'परधान'), ('Pardhi', 'पारधी'), ('Parja', 'परजा'), ('Saharaiya', 'सहरिया'), ('Saunta', 'सांता'), ('Saur', 'सौर'), ('Sawar', 'सावरा'), ('Sonr', 'सोंर')], default='Gond', max_length=100, verbose_name='जाति (Caste)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='शहर/ग्राम'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='complexion',
            field=models.CharField(choices=[('Fair', 'गोरा (Fair)'), ('Wheatish', 'सावला (Wheatish)'), ('Dark', 'काला (Dark)')], max_length=50, verbose_name='रंग (Complexion)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='जिला'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='education',
            field=models.CharField(choices=[('Primary', 'प्रारंभिक शिक्षा'), ('12th', '12वीं (बारहवीं)'), ('Graduation', 'स्नातक (Graduation)'), ('PG', 'स्नातोत्तर (PG)'), ('Other', 'अन्य (Other)')], max_length=100, null=True, verbose_name='शिक्षा (Education)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ईमेल'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='family_status',
            field=models.TextField(help_text='भाई-बहन की जानकारी', verbose_name='पारिवारिक स्थिति'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='father_name',
            field=models.CharField(max_length=255, verbose_name='पिता का नाम'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('Agriculture', 'कृषि (Agri)'), ('Job', 'नौकरी (Naukri)'), ('Business', 'व्यवसाय (Business)'), ('Other', 'अन्य (Anya)')], max_length=100, verbose_name='पिता का व्यवसाय'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male/पुरुष'), ('F', 'Female/महिला')], max_length=1, null=True, verbose_name='लिंग (Gender)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='gotra',
            field=models.CharField(choices=[('Nag', 'नाग (Nag)'), ('Bagh', 'बाघ (Bagh)'), ('Kachhua', 'कछुआ (Kachhua)'), ('Hans', 'हंस (Hans)'), ('Bhaisa', 'भैंसा (Bhaisa)'), ('Karait', 'करैत (Karait)'), ('Netam', 'नेताम (Netam)'), ('Markam', 'मरकाम (Markam)'), ('Tekam', 'टेकाम (Tekam)'), ('Koram', 'कोराम (Koram)'), ('Kunjam', 'कुंजाम (Kunjam)'), ('Poya', 'पोया (Poya)'), ('Mandavi', 'मंडावी (Mandavi)'), ('Sori', 'सोरी (Sori)'), ('Uikey', 'उईके (Uikey)'), ('Lakra', 'लकरा (Lakra)'), ('Minj', 'मिंज (Minj)'), ('Tirkey', 'तिर्की (Tirkey)'), ('Ekka', 'एक्का (Ekka)'), ('Kujur', 'कुजूर (Kujur)'), ('Toppo', 'टोप्पो (Toppo)'), ('Beck', 'बेक (Beck)'), ('Panna', 'पन्ना (Panna)'), ('Prahlad', 'प्रहलाद (Prahlad)'), ('Vashishtha', 'वशिष्ठ (Vashishtha)'), ('Kasyap', 'कश्यप (Kasyap)'), ('Neti', 'नेती (Neti)'), ('Kauva', 'कौवा (Kauva)')], max_length=100, verbose_name='गोत्र (Gotra)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='guardian_mobile',
            field=models.CharField(max_length=15, verbose_name='पालक का मोबाईल'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='सक्रिय है?'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='marital_status',
            field=models.CharField(choices=[('Unmarried', 'अविवाहित (Unmarried)'), ('Divorced', 'तलाकशुदा (Divorced)')], default='Unmarried', max_length=20, verbose_name='वैवाहिक स्थिति'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='mother_name',
            field=models.CharField(max_length=255, verbose_name='माता का नाम'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='occupation',
            field=models.CharField(choices=[('Agriculture', 'कृषि (Agri)'), ('Job', 'नौकरी (Naukri)'), ('Business', 'व्यवसाय (Business)'), ('Other', 'अन्य (Anya)')], default='Other', max_length=100, verbose_name='वर्तमान व्यवसाय'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='serial_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='सरल क्रमांक'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='state',
            field=models.CharField(default='Chhattisgarh', max_length=100, verbose_name='राज्य'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='weight',
            field=models.CharField(blank=True, choices=[('Underweight', 'कम वजन (50 किग्रा से कम)'), ('Average', 'मध्यम वजन (50 – 70 किग्रा)'), ('Overweight', 'अधिक वजन (70 किग्रा से अधिक)')], max_length=50, null=True, verbose_name='वजन (Weight)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='work_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='कार्य स्थल'),
        ),
    ]
