# Generated by Django 4.2 on 2026-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0007_remove_communitybiodata_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybiodata',
            name='caste',
            field=models.CharField(choices=[('Agariya', 'अगरिया'), ('Andh', 'अंध'), ('Baiga', 'बैगा'), ('Baina', 'बैना'), ('Bharia', 'भारिया भूमिया'), ('Bhattra', 'भतरा'), ('Bhil', 'भील'), ('Bhunjia', 'भुंजिया'), ('Gond', 'गोंड'), ('Halba', 'हल्बा'), ('Kawar', 'कंवर'), ('Khairwar', 'खैरवार'), ('Kharia', 'खड़िया'), ('Kol', 'कोल'), ('Korku', 'कोरकू'), ('Korwa', 'कोरवा'), ('Nagesia', 'नगेसिया'), ('Oraon', 'उरांव'), ('Pao', 'पाव'), ('Pardhan', 'परधान'), ('Saharaiya', 'सहरिया'), ('Sawar', 'सावरा')], default='Gond', max_length=100, verbose_name='जाति (Caste)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='complexion',
            field=models.CharField(blank=True, choices=[('Fair', 'गोरा (Fair)'), ('Wheatish', 'सावला (Wheatish)'), ('Dark', 'काला (Dark)')], max_length=50, null=True, verbose_name='रंग (Complexion)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='district',
            field=models.CharField(blank=True, choices=[('Raipur', 'Raipur (रायपुर)'), ('Durg', 'Durg (दुर्ग)'), ('Bilaspur', 'Bilaspur (बिलासपुर)'), ('Raigarh', 'Raigarh (रायगढ़)'), ('Jashpur', 'Jashpur (जशपुर)'), ('Surguja', 'Surguja (सरगुजा)'), ('Korba', 'Korba (कोरबा)'), ('Bastar', 'Bastar (बस्तर)'), ('Other', 'Other (अन्य)')], max_length=100, null=True, verbose_name='जिला'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='education',
            field=models.CharField(blank=True, choices=[('Primary', 'प्रारंभिक शिक्षा'), ('12th', '12वीं (बारहवीं)'), ('Graduation', 'स्नातक (Graduation)'), ('PG', 'स्नातकोत्तर (PG)'), ('Other', 'अन्य (Other)')], max_length=100, null=True, verbose_name='शिक्षा (Education)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('Agriculture', 'कृषि (Agri)'), ('Job', 'नौकरी (Naukri)'), ('Business', 'व्यवसाय (Business)'), ('Other', 'अन्य (Anya)')], max_length=100, null=True, verbose_name='पिता का व्यवसाय'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='gotra',
            field=models.CharField(choices=[('Nag', 'नाग (Nag)'), ('Bagh', 'बाघ (Bagh)'), ('Kachhua', 'कछुआ (Kachhua)'), ('Hans', 'हंस (Hans)'), ('Bhaisa', 'भैंसा (Bhaisa)'), ('Karait', 'करैत (Karait)'), ('Netam', 'नेताम (Netam)'), ('Markam', 'मरकाम (Markam)'), ('Tekam', 'टेकाम (Tekam)'), ('Lakra', 'लकरा (Lakra)'), ('Minj', 'मिंज (Minj)'), ('Tirkey', 'तिर्की (Tirkey)'), ('Ekka', 'एक्का (Ekka)'), ('Kujur', 'कुजूर (Kujur)'), ('Toppo', 'टोप्पो (Toppo)'), ('Prahlad', 'प्रहलाद (Prahlad)'), ('Vashishtha', 'वशिष्ठ (Vashishtha)'), ('Kasyap', 'कश्यप (Kasyap)')], max_length=100, verbose_name='गोत्र (Gotra)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='height',
            field=models.CharField(blank=True, choices=[('4\'0"', '4 फीट 0 इंच'), ('4\'1"', '4 फीट 1 इंच'), ('4\'2"', '4 फीट 2 इंच'), ('4\'3"', '4 फीट 3 इंच'), ('4\'4"', '4 फीट 4 इंच'), ('4\'5"', '4 फीट 5 इंच'), ('4\'6"', '4 फीट 6 इंच'), ('4\'7"', '4 फीट 7 इंच'), ('4\'8"', '4 फीट 8 इंच'), ('4\'9"', '4 फीट 9 इंच'), ('4\'10"', '4 फीट 10 इंच'), ('4\'11"', '4 फीट 11 इंच'), ('5\'0"', '5 फीट 0 इंच'), ('5\'1"', '5 फीट 1 इंच'), ('5\'2"', '5 फीट 2 इंच'), ('5\'3"', '5 फीट 3 इंच'), ('5\'4"', '5 फीट 4 इंच'), ('5\'5"', '5 फीट 5 इंच'), ('5\'6"', '5 फीट 6 इंच'), ('5\'7"', '5 फीट 7 इंच'), ('5\'8"', '5 फीट 8 इंच'), ('5\'9"', '5 फीट 9 इंच'), ('5\'10"', '5 फीट 10 इंच'), ('5\'11"', '5 फीट 11 इंच'), ('6\'0"', '6 फीट 0 इंच'), ('6\'1"', '6 फीट 1 इंच'), ('6\'2"', '6 फीट 2 इंच'), ('6\'3"', '6 फीट 3 इंच'), ('6\'4"', '6 फीट 4 इंच'), ('6\'5"', '6 फीट 5 इंच'), ('6\'6"', '6 फीट 6 इंच'), ('6\'7"', '6 फीट 7 इंच'), ('6\'8"', '6 फीट 8 इंच'), ('6\'9"', '6 फीट 9 इंच'), ('6\'10"', '6 फीट 10 इंच'), ('6\'11"', '6 फीट 11 इंच'), ('7\'0"', '7 फीट')], max_length=20, null=True, verbose_name='कद (Height)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='state',
            field=models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh (छत्तीसगढ़)'), ('Madhya Pradesh', 'Madhya Pradesh (मध्य प्रदेश)'), ('Maharashtra', 'Maharashtra (महाराष्ट्र)'), ('Odisha', 'Odisha (ओडिशा)'), ('Other', 'Other (अन्य)')], default='Chhattisgarh', max_length=100, verbose_name='राज्य'),
        ),
    ]
