# Generated by Django 4.2 on 2026-03-07 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0008_alter_communitybiodata_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybiodata',
            name='candidate_mobile',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be between 10 to 15 digits.', regex='^\\d{10,15}$')], verbose_name='स्वयं का मोबाईल'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='district',
            field=models.CharField(blank=True, choices=[('Balod', 'Balod (बालोद)'), ('Baloda Bazar', 'Baloda Bazar (बलौदा बाजार)'), ('Balrampur', 'Balrampur (बालरामपुर)'), ('Bastar', 'Bastar (बस्तर)'), ('Bemetara', 'Bemetara (बेमेतरा)'), ('Bijapur', 'Bijapur (बीजापुर)'), ('Bilaspur', 'Bilaspur (बिलासपुर)'), ('Dantewada', 'Dantewada (दंतेवाड़ा)'), ('Dhamtari', 'Dhamtari (धमतरी)'), ('Durg', 'Durg (दुर्ग)'), ('Gariaband', 'Gariaband (गरियाबंद)'), ('Gaurela-Pendra-Marwahi', 'Gaurela-Pendra-Marwahi (गौरेला-पेंड्रा-मरवाही)'), ('Janjgir-Champa', 'Janjgir-Champa (जांजगीर-चांपा)'), ('Jashpur', 'Jashpur (जशपुर)'), ('Kabirdham', 'Kabirdham (कबीरधाम)'), ('Kanker', 'Kanker (कांकेर)'), ('Kondagaon', 'Kondagaon (कोंडागांव)'), ('Korba', 'Korba (कोरबा)'), ('Korea', 'Korea (कोरिया)'), ('Mahasamund', 'Mahasamund (महासमुंद)'), ('Manendragarh-Chirmiri-Bharatpur', 'Manendragarh-Chirmiri-Bharatpur (मनेंद्रगढ़-चिरमिरी-भरतपुर)'), ('Mohla-Manpur-Ambagarh Chowki', 'Mohla-Manpur-Ambagarh Chowki (मोहला-मानपुर-अंबागढ़ चौकी)'), ('Mungeli', 'Mungeli (मुंगेली)'), ('Narayanpur', 'Narayanpur (नारायणपुर)'), ('Raigarh', 'Raigarh (रायगढ़)'), ('Raipur', 'Raipur (रायपुर)'), ('Rajnandgaon', 'Rajnandgaon (राजनांदगांव)'), ('Sakti', 'Sakti (सक्ती)'), ('Sarangarh-Bilaigarh', 'Sarangarh-Bilaigarh (सारंगढ़-बिलाईगढ़)'), ('Sukma', 'Sukma (सुकमा)'), ('Surajpur', 'Surajpur (सूरजपुर)'), ('Surguja', 'Surguja (सरगुजा)'), ('Khairagarh-Chhuikhadan-Gandai', 'Khairagarh-Chhuikhadan-Gandai (खैरागढ़-छुईखदान-गंडई)'), ('Other', 'Other (अन्य)')], max_length=100, null=True, verbose_name='जिला'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='पूरा नाम (Full Name)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='guardian_mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be between 10 to 15 digits.', regex='^\\d{10,15}$')], verbose_name='पालक का मोबाईल'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='सक्रिय है?'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='state',
            field=models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh (छत्तीसगढ़)'), ('Other', 'Other (अन्य)')], default='Chhattisgarh', max_length=100, verbose_name='राज्य'),
        ),
    ]
