# Generated by Django 4.2 on 2026-03-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0010_communitybiodata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitybiodata',
            options={},
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='complexion',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='district',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='communitybiodata',
            name='work_location',
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='caste',
            field=models.CharField(choices=[('Gond', 'गोंड'), ('Halba', 'हल्बा'), ('Kawar', 'कंवर'), ('Oraon', 'उरांव'), ('Other', 'अन्य')], default='Gond', max_length=100, verbose_name='जाति (Caste)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='gotra',
            field=models.CharField(choices=[('Nag', 'नाग (Nag)'), ('Bagh', 'बाघ (Bagh)'), ('Netam', 'नेताम (Netam)'), ('Markam', 'मरकाम (Markam)')], max_length=100, verbose_name='गोत्र (Gotra)'),
        ),
    ]
