# Generated by Django 4.2 on 2026-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0011_alter_communitybiodata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybiodata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='शहर/ग्राम'),
        ),
    ]
