# Generated by Django 4.2 on 2026-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0012_communitybiodata_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitybiodata',
            name='district',
            field=models.CharField(blank=True, choices=[('Balod', 'Balod (बालोद)'), ('Baloda Bazar', 'Baloda Bazar (बलौदा बाजार)'), ('Balrampur', 'Balrampur (बालरामपुर)'), ('Bastar', 'Bastar (बस्तर)'), ('Bemetara', 'Bemetara (बेमेतरा)'), ('Bijapur', 'Bijapur (बीजापुर)'), ('Bilaspur', 'Bilaspur (बिलासपुर)'), ('Dantewada', 'Dantewada (दंतेवाड़ा)'), ('Dhamtari', 'Dhamtari (धमतरी)'), ('Durg', 'Durg (दुर्ग)'), ('Gariaband', 'Gariaband (गरियाबंद)'), ('Janjgir-Champa', 'Janjgir-Champa (जांजगीर-चांपा)'), ('Korba', 'Korba (कोरबा)'), ('Raigarh', 'Raigarh (रायगढ़)'), ('Raipur', 'Raipur (रायपुर)'), ('Other', 'Other (अन्य)')], max_length=100, null=True, verbose_name='जिला'),
        ),
        migrations.AddField(
            model_name='communitybiodata',
            name='state',
            field=models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh (छत्तीसगढ़)'), ('Other', 'Other (अन्य)')], default='Chhattisgarh', max_length=100, verbose_name='राज्य'),
        ),
    ]
