# Generated by Django 4.2 on 2026-03-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0013_communitybiodata_district_communitybiodata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybiodata',
            name='caste',
            field=models.CharField(choices=[('Agariya', 'अगरिया'), ('Andh', 'अंध'), ('Baiga', 'बैगा'), ('Baina', 'बैना'), ('Bharia', 'भारिया भूमिया'), ('Bhattra', 'भतरा'), ('Bhil', 'भील'), ('Bhunjia', 'भुंजिया'), ('Gond', 'गोंड'), ('Halba', 'हल्बा'), ('Kawar', 'कंवर'), ('Khairwar', 'खैरवार'), ('Kharia', 'खड़िया'), ('Kol', 'कोल'), ('Korku', 'कोरकू'), ('Korwa', 'कोरवा'), ('Nagesia', 'नगेसिया'), ('Oraon', 'उरांव'), ('Pao', 'पाव'), ('Pardhan', 'परधान'), ('Saharaiya', 'सहरिया'), ('Sawar', 'सावरा')], default='Gond', max_length=100, verbose_name='जाति (Caste)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='gotra',
            field=models.CharField(choices=[('Nag', 'नाग (Nag)'), ('Bagh', 'बाघ (Bagh)'), ('Kachhua', 'कछुआ (Kachhua)'), ('Hans', 'हंस (Hans)'), ('Bhaisa', 'भैंसा (Bhaisa)'), ('Karait', 'करैत (Karait)'), ('Netam', 'नेताम (Netam)'), ('Markam', 'मरकाम (Markam)'), ('Tekam', 'टेकाम (Tekam)'), ('Lakra', 'लकरा (Lakra)'), ('Minj', 'मिंज (Minj)'), ('Tirkey', 'तिर्की (Tirkey)'), ('Ekka', 'एक्का (Ekka)'), ('Kujur', 'कुजूर (Kujur)'), ('Toppo', 'टोप्पो (Toppo)'), ('Prahlad', 'प्रहलाद (Prahlad)'), ('Vashishtha', 'वशिष्ठ (Vashishtha)'), ('Kasyap', 'कश्यप (Kasyap)')], max_length=100, verbose_name='गोत्र (Gotra)'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='सक्रिय है?'),
        ),
        migrations.AlterField(
            model_name='communitybiodata',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
